### ISSUE TITLE
what do you think if we'll move all stuff, related to calendar into a separated repository? 

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-23#70]
can you create some sort of a plan, like what components we should move, etc.
Imagine this case - you create a clean step by step plan and we move that task to a some of our new interns, so they can have some practice, while working on code from other people. i mean it should be very clear, or it'll generate a lot of questions, and will be a bit complex. because when you just learning - it's hard to jump into a project, usually.

**Comment by atherdon** [comment]
i created a repo here: https://github.com/ChickenKyiv/meal-calendar

**Comment by sanchit94** [comment]
Okay, will look into this and inform you regarding the plan!

**Comment by sanchit94** [comment]
### Meal Calendar Tasks

**Task 1:** Go on the internet and learn and practice about high-order functions in javascript, specially map, reduce and filter. This is because we will extensively use them in react for any list related tasks, since React does not have ngFor like angular for displaying list elements. This will also enhance functional programming knowledge which is very essential in React. If you already know about them you can skip this one and move to the next task.

**Task 2:** Create a list with 10 empty(blank) list items(li) and format it such that each li has a height of 50px, and borders, such that it looks like a blank table where you can fill up data. However, you cannot just write 10 lis, you will have to use one of high-order functions to get this task done.

**Task 3:** Change your code for the lis such that the 3rd, 5th, and 8th li in the list group has a height 75px. Also make sure that the total height of the list group should remain the same, i.e., 500px. This means you will have to adjust height of the remaining lis accordingly. For e.g. since the 3rd li has height of 75px, the 4th li will have height only 25px, and vice versa. This has to be done again using high-order functions only.

**Comment by atherdon** [comment]
i like it - keep going! maybe after 10-12 tasks i'll make some adjustments and comments.

i think i should explain why i decide to create such assignment to you. i plan to change hierarchy in our company. Basically right now i'm managing at least 10-12 people in a row(and this number growing each month), and usually i don't have a lot of time for tasks, that  related to "big picture planning". and you're doing pretty well here, so i plan to make you a leader of a few interns(one from start) and you'll be a main person that track the progress and communicate with that part of team. i think it's a cool way to grow

**Comment by sanchit94** [comment]
That would be really good, and yes I agree it's a really great way to grow. I will keep this in mind and 'invent' some other tasks as well!! :)

**Comment by atherdon** [comment]
will give you one hint - setup nodejs server :)
